### PR TITLE
Updated CustomSkulls to 1.4.7

### PR DESCRIPTION
**Pull request by PatPeter**
I modified several parts of your plugin from not loading on server start to a very confusing give statement, as well as a more easily memorized command alias /skulls (I kept thinking /cs but that's WorldEdit. I never would have remembered /ck).

The rest of the changes can be seen here:
https://github.com/PatPeter/CustomSkulls

### CODE REVIEW

**Comment by timvisee** [comment]
What did you do to the Permissions Manager? It looks like it has been removed with this pull request. The Permissions Manager is a major component of the plugin!
Also, about the command 'Skulls', fine, sounds better than /cs indeed.

It looks like you replaced the permissions system with a build in one. The fact is that the Permissions Manager works way better and supports more plugins. Also in our newer version of the class it even supports 2 more plugins. I won't remove the permissions manager cause of this.

**Comment by Erackron** [comment]
Removing the permissionsmanager because it does what Valt does is not really a valid reason, because that way you force people to use Vault if they want to use a permissions system. This also creates a dependency for the plugin you put it in, so if the author of Vault ever decides to stop developing without looking for anyone to take over, the plugin won't support permissions anymore.
So yes, basically, the permissionsmanager does the same as Vault, but does not require an additional plugin, and we develop it ourselves, so it is less likely to get abandoned when we still develop plugins that use it.

**Comment by timvisee** [comment]
Thanks Erackron. This is indeed the exact reason why I put in the Permissions Manager class.
Again, the skulls command sounds great. Since I already have a new version (updated by @Pyriphlegethon) with serval new features, which haven't been uploaded to GitHub yet, I will add the command to the plugin manually.
I will also apply the update of probablity thought.
- Tim Visée

**Comment by PatPeter** [comment]
> because that way you force people to use Vault if they want to use a permissions system

You already have Vault as a softdepend in the plugin.yml as well as a supported permission in PermissionsManager: that's redundant. I see your point that you don't want people downloading an extra jar, but with Vault there is a high probability they've already downloaded it for another plugin. Also, with the 9 staff Vault has, I can confidently tell you that Vault will never die.

> Again, the skulls command sounds great.

That's the fifth point on my changelog, and since my first point is now invalid, how about the other 9? If you didn't already have a newer version, I would add PermissionsManager back in so that you could accept the pull request.

https://github.com/PatPeter/CustomSkulls/blob/master/README

**Comment by wfdewith** [comment]
I have an unsynced version on my pc. That version contains an updated give command. I also fixed the bug with Wither/Wither Skeleton. I agree with you about the mess in the CommandHandler.

**Comment by Erackron** [comment]
> You already have Vault as a softdepend in the plugin.yml as well as a supported permission in PermissionsManager: that's redundant.

I hope you do realise the big difference between depend and softdepend?
Depend means: if any plugin(s) listed here is/are not found, your plugin will not load,
whereas softdepend means: if the plugin(s) listed here is/are found, load them before this plugin.
[Plugin.yml](http://wiki.bukkit.org/Plugin_YAML) on the bukkit wiki

**Comment by wfdewith** [comment]
I will use your code to create a manual commit, which will include my changes as well. We can choose which parts we want to use then.

**Comment by wfdewith** [comment]
> That's the fifth point on my changelog, and since my first point is now invalid, how about the other 9?

I think your updates on the give command is quite good and I will use it for sure. Your updates on the readability are also great, so I will add them as well. I (and timvisee and Erackron) will use the Permissions Manager as stated above.

**Comment by timvisee** [comment]
@PatPeter / @Pyriphlegethon , do you have any update yet. It would be cool if any update could be pulled. This shows me the current status of the plugin. I currently don't think there's anything to do for me. The fact is that I have to upload a new version as soon as possible. The plugin is already a few weeks outdated which is very bad for the reputation.

Thanks in advance,
Tim Visée

**Comment by wfdewith** [comment]
@timvisee
I pushed a new version yesterday, including all changes by @PatPeter that I want to keep. I haven't tested it yet and you should take a look in the changes.

**Comment by timvisee** [comment]
Yes sure, because you don't need a pull verification I didn't noticed it, sorry. Thanks btw.

**Comment by PatPeter** [comment]
> I hope you do realise the big difference between depend and softdepend?

Fully aware.

Also, so that I don't have to make a new ticket, these lines of code should be deleted:

```
for(ItemStack entry : e.getDrops()) 
  if(entry.getTypeId() == 144 || entry.getTypeId() == 397)
    entry.setAmount(0);
```

In onPlayerDeathEvent() in CustomSkullsEntityListener. I'm aware that it's supposed to cancel a skull drop that's already there, but all it does is delete all the heads that player was grinding to get. A few players on my server died with full stacks of heads and lost them.

Also @Pyriphlegethon you should push the config.yml to the repository.

**Comment by wfdewith** [comment]
> Also @Pyriphlegethon you should push the config.yml to the repository.

I did.

> In onPlayerDeathEvent() in CustomSkullsEntityListener. I'm aware that it's supposed to cancel a skull drop that's already there, but all it does is delete all the heads that player was grinding to get. A few players on my server died with full stacks of heads and lost them.

I thought @timvisee fixed that bug, but apparently I am wrong. I don't know if @timvisee wants to delete those lines so I will wait for his permission.

**Comment by timvisee** [comment]
Well, actually I did fixed the problem, but somehow it hasn't been pushed to GitHub for no reason. I will delete them manually since I'm syncing the project again to make it ready for a new release. Also, these lines shouldn't been removed inside the entity die event, when a wither skeleton dies, cause it can naturally drop his own skull. I actually think you already knew this, but I just wanted to say it before your asking ;)

Anyhow, of course, as soon as I've released the project I will push the last few things I've changed before the next release.

Tim Visée

**Pull request closed without merging**
